model:
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  channels:
    - 4
    - 8
    - 16
    - 32
    - 64
  strides:
    - - 3
      - 4
      - 4
    - - 2
      - 2
      - 4
    - 2
    - 2
  num_res_units: 2

dataset:
  image_path: "/data/train/"
  mask_path: "data/nrrd_heart/nrrd_heart/"

trainer:
  epochs: 100
  lr: 0.001
  batch_size: 8
  num_workers: 4
  output_dir: "/data/output/"
  log_dir: "/data/output/logs/"
  checkpoint_dir: "/data/output/checkpoints/"
  plot: True
  checkpoint_interval: 5
