model:
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  dropout_prob: 0.2
  channels:
    - 4
    - 8
    - 16
    - 32
    - 64
  strides_custom:
    - 2
    - 2
    - 2
    - 2
    - 2
  strides:
    - - 4
      - 4
      - 2
    - - 2
      - 2
      - 2
    - 2
    - 2
  num_res_units: 2
  model_type: 1 # 0 is for monai UNET, 1 is for Custom Unet (i made)



optimizer:
  name: "Adam"
  params:
    lr: 0.001
    weight_decay: 0.0001

  scheduler:
    name: torch.optim.Adam
    params:
      mode: "min"
      factor: 0.5
      patience: 10

dataset:
  image_path:
    - "../../../datasets/tdt4265/mic/asoca/Diseased/CTCA/"
    - "../../../datasets/tdt4265/mic/asoca/Normal/CTCA/"
  mask_path:
    - "../../../datasets/tdt4265/mic/asoca/Diseased/Annotations/"
    - "../../../datasets/tdt4265/mic/asoca/Normal/Annotations/"
  cache_dataset: True
trainer:
  epochs: 50
  lr: 0.0001
  batch_size: 8
  num_workers: 0
  output_dir: "./data/output/"
  log_dir: "./data/output/logs/"
  checkpoint_dir: "./data/output/checkpoints/"
  plot: False
  checkpoint_interval: 5
